FROM jenkins/jenkins

USER root

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    apt-get update -y && \
    apt-get -y install python3 && \
    python3 get-pip.py && \
    pip3 install ansible --upgrade

#install docker
RUN apt-get update -y && \
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && \
    apt-get update -y && \
    apt-cache policy docker-ce && \
    apt-get install -y docker-ce
#install docker-compose

RUN  curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
     chmod +x /usr/local/bin/docker-compose

RUN usermod -aG docker jenkins

USER jenkins
